---
format_version: '8'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios
app:
  envs:
  - BITRISE_PROJECT_PATH: standard-swift.xcodeproj
  - BITRISE_SCHEME: standard-swift
  - BITRISE_EXPORT_METHOD: ad-hoc
trigger_map:
- push_branch: "*"
  workflow: primary
- pull_request_source_branch: "*"
  workflow: primary
workflows:
  primary:
    steps:
    - activate-ssh-key@4.0.3:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@4.0.17: {}
    - cache-pull@2.1.0: {}
    - script@1.1.5:
        title: Do anything with Script step
    - certificate-and-profile-installer@1.10.1: {}
    - script:
        title: build and test
        timeout: 1500
        inputs:
        - content: |-
            set -euxo pipefail
            xcodebuild -project standard-swift.xcodeproj/ -scheme standard-swift \
                -derivedDataPath Build/ \
                -destination 'platform=iOS Simulator,OS=13.4.1,name=iPhone 8' \
                -enableCodeCoverage YES clean build test \
                CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    - script:
        title: generate code coverage report to xml format
        inputs:
        - content: |-
            set -euxo pipefail
            if ! which slather >/dev/null 2>&1; then \
                echo "install slather"; \
                gem install slather
            fi

            # slather will search local .slather.yml config file
            # the xml format report will be in local ./report dir
            slather coverage -b Build/
    - codecov@1:
        inputs:
        - other_options: "-s ./report"
        - CODECOV_TOKEN: "$CODECOV_UPLOAD_TOKEN"
    - deploy-to-bitrise-io@1.7.1: {}
    - cache-push@2.2.0: {}
